FROM ubuntu:jammy
ARG DEBIAN_FRONTEND=noninteractive
ARG TZ="Asia/Shanghai"

# Install Base Lib
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
		libgl1-mesa-dri \
    	libglx-mesa0 \
    	libgl1-mesa-glx \
    	libglapi-mesa \
    	libgbm1 \
    	libegl-mesa0 \
    	libgl1-mesa-dri \
    	libglx-mesa0 \
		apt-file \
		tcsh tclsh xfonts-base libssl-dev\
		tclsh \
        gsl-bin netpbm gnome-tweaks \
        libjpeg62 xvfb xterm vim curl \
        gedit evince eog \
        libglu1-mesa-dev libglw1-mesa \
        libxm4 build-essential \
        libcurl4-openssl-dev libxml2-dev \
        libgfortran-11-dev libgomp1 \
        gnome-terminal nautilus \
        firefox xfonts-100dpi \
        r-base-dev cmake \
        libgdal-dev libopenblas-dev \
		libnode-dev libudunits2-dev \
		build-essential \
		zlib1g-dev \
		libbz2-1.0 \
		librust-bzip2-dev \
		liblzma-dev \
		xvfb \
		libgomp1 \
		binutils \
		tzdata \
		bzip2 \
		ca-certificates \
		curl \
		unzip \
		less \
		vim \
		vim-gui-common \
		mesa-utils \
		qtbase5-dev \
		xauth \
		libnss3 \
		libpci-dev \
		libxcomposite1 \
		libxdamage1 \
		libxrandr2 \
		libxcursor1 \
		libxi6 \
		libxtst6 \
		libasound2 \
		libafterimage0 \
		openjdk-8-jre autoconf \
		language-pack-zh-hans fonts-droid-fallback ttf-wqy-zenhei \
		ttf-wqy-microhei fonts-arphic-ukai fonts-arphic-uming \
		mricron && \
	apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN ln -s /usr/lib/x86_64-linux-gnu/libgsl.so.27 /usr/lib/x86_64-linux-gnu/libgsl.so.19

# Support zh_CN
RUN echo "LANG=\"zh_CN.UTF-8\"" >> /etc/environment && \
	echo "LANGUAGE=\"zh_CN:zh:en_US:en\"" >> /etc/environment && \
	echo "en_US.UTF-8 UTF-8" >> /var/lib/locales/supported.d/local && \
	echo "zh_CN.UTF-8 UTF-8" >> /var/lib/locales/supported.d/local && \
	echo "zh_CN.GBK GBK" >> /var/lib/locales/supported.d/local && \
	echo "zh_CN GB2312" >> /var/lib/locales/supported.d/local && \
	locale-gen

RUN curl -O https://repo.anaconda.com/miniconda/Miniconda3-py39_23.11.0-2-Linux-x86_64.sh && \
	bash Miniconda3-py39_23.11.0-2-Linux-x86_64.sh -b -p /opt/conda
ENV PATH="$PATH:/opt/conda/bin:/opt/conda/condabin"
RUN /opt/conda/bin/conda init
RUN conda update -y conda && \
	conda install -n base conda-libmamba-solver && \
    conda config --set solver libmamba && \
	conda install -y mamba -n base -c conda-forge
RUN pip install spyder

WORKDIR /tmp
# useradd -m -G adm,dialout,cdrom,floppy,audio,dip,video,plugdev -s /bin/bash sandy
